# Generated by Django 4.2.3 on 2023-08-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_app', '0002_mp3file_name_alter_mp3file_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MP3File',
        ),
    ]
