# Generated by Django 4.2.3 on 2023-09-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_app', '0003_convertedaudio_delete_mp3file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_playing', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ConvertedAudio',
        ),
    ]
